LOCAL_PATH := device/xiaomi/beryl

TARGET_ARCH := arm64
TARGET_CPU_ABI := arm64-v8a
TARGET_BOARD_PLATFORM := mt6878
TARGET_NO_KERNEL := false

# Vendor Boot & Decryption Configuration
BOARD_USES_VENDOR_BOOT := true
BOARD_MOVE_RECOVERY_RESOURCES_TO_VENDOR_BOOT := true
BOARD_INCLUDE_RECOVERY_DTBO_IN_VENDOR_BOOT := true
BOARD_BOOTIMG_HEADER_VERSION := 4
BOARD_KERNEL_BASE := 0x00000000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_KERNEL_CMDLINE := bootconfig

# Storage & File-Based Encryption (FBE v2)
BOARD_SUPPORTS_EXT4 := true
BOARD_SUPPORTS_F2FS := true
TARGET_USERIMAGES_USE_F2FS := true
TW_INCLUDE_CRYPTO := true
TW_INCLUDE_CRYPTO_FBE := true
TW_USE_FS_CRYPT_H := true
BOARD_USES_METADATA_PARTITION := true

# Screen & UI
TW_THEME := portrait_ds
TARGET_SCREEN_WIDTH := 1080
TARGET_SCREEN_HEIGHT := 2400
